// spec: homepage_test_plan.md
// seed: tests/seed.spec.ts

import { test, expect } from '@playwright/test';

test.describe('Homepage Functionality', () => {
  test('Verify homepage loads correctly', async ({ page }) => {
    // 1. Navigate to the homepage URL
    await page.goto('https://salespulse-ai-b7acd.web.app/');

    // expect: Page title is 'SalesPulse AI'
    await expect(page).toHaveTitle('SalesPulse AI');

    // expect: URL is 'https://salespulse-ai-b7acd.web.app/'
    await expect(page).toHaveURL('https://salespulse-ai-b7acd.web.app/');

    // expect: Header elements are visible: logo
    await expect(page.getByText('SalesPulseAI')).toBeVisible();

    // expect: Header elements are visible: Help & Features button
    await expect(page.getByRole('button', { name: 'Help & Features' })).toBeVisible();

    // expect: Header elements are visible: Sign In button
    await expect(page.getByRole('button', { name: 'Sign In' })).toBeVisible();

    // expect: Main content is displayed: heading
    await expect(page.getByText('Unlock insights from every conversation')).toBeVisible();

    // expect: Main content is displayed: description
    await expect(page.getByText('Upload your sales recordings. Get instant transcriptions, sentiment tracking, and actionable coaching tips generated by AI.')).toBeVisible();

    // expect: Main content is displayed: upload area
    await expect(page.getByText('Upload Sales Call')).toBeVisible();

    // expect: Main content is displayed: sign-in prompt
    await expect(page.getByText('Sign in to save your assessments and access them later!')).toBeVisible();

    // 2. Check the default selected option in the model combobox
    // expect: Model selector shows 'Gemini 3.0 Flash (Fastest)' as default
    await expect(page.getByRole('combobox')).toContainText('Gemini 3.0 Flash (Fastest)');
  });
});